### ISSUE TITLE
Setting `timeout` to floating point value < 1

### ISSUE THREAD

**Issue by 907th** [taf2/curb#355]
When I try to set `timeout` to floating point value, the client converts it to the integer value and ignores it if the value is less than 1:

```
c = Curl::Easy.new
c.timeout = 1.5
puts c.timeout # => 1
c.timeout = 0.5
puts c.timeout # => nil
```

This behaviour is somewhat unexpected and may lead to bugs in client applications. E.g. `Net::HTTP` client supports floating point values in timeouts.

**Comment by 907th** [comment]
After reading docs I see now that `#timeout=` expects `fixnum` value and that there is `#timeout_ms=` method for millisecond values. Please, close this issue If you consider this one an expected behaviour.

**Comment by robuye** [comment]
This closely reflects low level `libcurl` implementation and sets `CURLOPT_TIMEOUT_MS` or `CURLOPT_TIMEOUT` respectively, but there is no reason to ever use `CURLOPT_TIMEOUT` over `CURLOPT_TIMEOUT_MS` as far as I know.

`CURLOPT_TIMEOUT_MS` has been added in curl version 7.16.2 (released  2007) and `--max-time` option uses it as of curl version 7.32.0 (released 2013).

The `curl` implementation is simply `my_setopt(curl, CURLOPT_TIMEOUT_MS, (long)(config->timeout * 1000));` where `config->timeout` is a `double` specified with the `--max-time` flag (https://github.com/curl/curl/commit/d8c04909fa50e87bba58311dd8feecaa94508f4b).

I think it's best to stop using `CURLOPT_TIMEOUT` entirely and change the `timeout=` method to work with floats and use `CURLOPT_TIMEOUT_MS` (and adjust the getter respectively).

The behaviour should not change even if someone would set both `timeout` and `timeout_ms` because `libcurl` always uses the value last set:

> If both CURLOPT_TIMEOUT and CURLOPT_TIMEOUT_MS are set, the value set last will be used.

**Comment by taf2** [comment]
I agree this is unexpected... we should probably internally handle this by using timeout_ms automatically...
