### ISSUE TITLE
Using curb on Windows

### ISSUE THREAD

**Issue by volkanunsal** [taf2/curb#37]
I am trying to install the curb gem. Since I need to have "A working (lib)curl installation, with development stuff" installed on my computer, I went to the cURL Download Wizard and downloaded this package.

But adding the bin into my PATH did not produce improvement and I still got an error when I try to install the curb gem, such as:

```
extconf.rb:19: Can't find libcurl or curl/curl.h (RuntimeError)
```

Even though, curl is already in the PATH.

I also tried raking the gem with this command:

`rake install EXTCONF_OPTS='--with-curl-dir=B:\curl'`

But all it fails saying "make failed" and throwing a bunch of errors like this:

```
C:/Ruby/lib/ruby/gems/1.8/gems/curb-0.7.7.1/ext/curb_postfield.c:76: undefined reference to 'imp_curl_formadd'
```

**Comment by abdufarag** [comment]
I have tried every thing but still cant install curb on Windows 10
C:\>gem install curb -- --with-curl-lib="C:/curl-7.27.0-devel-mingw32/bin" --with-curl-include="C:/curl-7.27.0-devel-mingw32/include"
Temporarily enhancing PATH to include DevKit...
Building native extensions with: '--with-curl-lib=C:/curl-7.27.0-devel-mingw32/bin --with-curl-include=C:/curl-7.27.0-devel-mingw32/include'
This could take a while...
ERROR:  Error installing curb:
        ERROR: Failed to build gem native extension.

    C:/Ruby22-x64/bin/ruby.exe -r ./siteconf20170418-13264-4p5aww.rb extconf.rb --with-curl-lib=C:/curl-7.27.0-devel-mingw32/bin --with-curl-include=C:/curl-7.27.0-devel-mingw32/include
checking for curl-config... no
checking for main() in -lcurl... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby22-x64/bin/$(RUBY_BASE_NAME)
        --with-curl-dir
        --without-curl-dir
        --with-curl-include=${curl-dir}/include
        --with-curl-lib=${curl-dir}/lib
        --with-curllib
        --without-curllib
extconf.rb:18:in `<main>':   Can't find libcurl or curl/curl.h (RuntimeError)

  Try passing --with-curl-dir or --with-curl-lib and --with-curl-include
  options to extconf.

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/curb-0.9.3 for inspection.
Results logged to C:/Ruby22-x64/lib/ruby/gems/2.2.0/extensions/x64-mingw32/2.2.0/curb-0.9.3/gem_make.out
