### ISSUE TITLE
Curl Instance unable to call DELETE method with Payload

### ISSUE THREAD

**Issue by luke-hill** [taf2/curb#384]
I believe the issue stems from the following 2 code snippets

```
      def http_post(*args)
        url = args.shift
        c = Curl::Easy.new url
        yield c if block_given?
        c.http_post(*args)
        c
      end
```

And

```
      def http_delete(*args)
        c = Curl::Easy.new(*args)
        yield c if block_given?
        c.http_delete
        c
      end
```

On the bottom example we cannot pass (*args), to the instance method of http_delete on the Easy instance. Which causes problems. I need to pass a JSON payload body to this method.

I've tried using the othe rinstance methods but it just trips me up. I want to be able to instantiate a Blank Easy with a Url. And then call `instance.http_delete(BODY.to_json)`

cc/ @robuye / @taf2 - I've had a good look through the code, I think it's just because the HTTP spec has changed from 2015ish and this library perhaps hasn't been updated? Or I could be wrong and this all could be possible

**Comment by robuye** [comment]
Hey @luke-hill,

I think you're right and it's not as uncommon to include payload with `DELETE` nowadays as it used to be some years ago.

Kubernetes API is one example where the server expects a payload with DELETE: https://docs.openshift.com/container-platform/3.7/rest_api/api/v1.Pod.html#Delete-api-v1-namespaces-namespace-pods-name

I think it should behave like a POST request and use CURLOPT_CUSTOMREQUEST to change the verb only. libcurl documentation at https://curl.haxx.se/libcurl/c/CURLOPT_CUSTOMREQUEST.html feels very relevant:

> Instead of GET or HEAD when performing HTTP based requests. This is particularly useful, for example, for performing an HTTP DELETE request.
> 
> For example:
> 
> When you tell libcurl to do a HEAD request, but then specify a GET though a custom request libcurl will still act as if it sent a HEAD. To switch to a proper HEAD use CURLOPT_NOBODY, to switch to a proper POST use CURLOPT_POST or CURLOPT_POSTFIELDS and to switch to a proper GET use CURLOPT_HTTPGET.
> 
> Many people have wrongly used this option to replace the entire request with their own, including multiple headers and POST contents. While that might work in many cases, it will cause libcurl to send invalid requests and it could possibly confuse the remote server badly. Use CURLOPT_POST and CURLOPT_POSTFIELDS to set POST data. Use CURLOPT_HTTPHEADER to replace or extend the set of headers sent by libcurl. Use CURLOPT_HTTP_VERSION to change HTTP version.

I checked curb `http_post` implementation (in C) and I think it would require changes to make it work, but not significant. Check it out too if you haven't already.

On the other hand you can make a DELETE request with body without any code changes, but this isn't very elegant or documented. This worked for me:

```ruby
easy = Curl::Easy.new("http://localhost:8081/echo") do|c|
  c.post_body = 'hello world'
  c.delete = true
end
easy.perform

easy.body_str
# => "DELETE /echo HTTP/1.1\r\nHost: localhost:8081\r\nAccept: */*\r\nContent-Length: 11\r\nContent-Type: application/x-www-form-urlencoded\r\n\r\n\nhello world\n"
```
The `easy.body_str` is echoed request, I have a small echo-server for debugging requests this way. It shows the server received DELETE and the body as expected.

So it looks like it could be fixed by just changing `http_delete` definition without every leaving ruby land, but I think refactoring C codebase would be more beneficial long term.

**Comment by luke-hill** [comment]
Rightio, I'll try the one you suggested, I saw that delete boolean flag earlier, but I could get it working. But I never realised to do it this way (Set as GET, add post body flag, then add delete flag)

Usually for posts I just do `c.http_post(body.to_json)` - Give me a couple of days to debug this and see if I can get something working my end.
